# This is a sample build configuration for Javascript (Node.js).
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - node --version
          - npm --version
          - pwd
          - whoami
          - ls -la
          - npm install
          - npm install yarn -g
          - npm install phantomjs -g
          - npm install bower -g
          - bower install --allow-root
          - yarn install
          - ./node_modules/karma/bin/karma start karma.conf.js #npm test
          - ./node_modules/.bin/documentation readme js/ --section=Wiki && ./node_modules/.bin/documentation build -f md ./bower_components/flyd/lib/index.js > API.md && ./node_modules/.bin/documentation build js/** -f html -o docs #npm run docs
